POST http://localhost:5000/api/sendOtp HTTP/1.1
Content-Type: application/json

{
    "phone":"+91 8451284512"
}

###
POST http://localhost:5000/api/verifyOtp HTTP/1.1
Content-Type: application/json

{
  "hash": "40ee06c7607fa8e07b1e7d9a0cc493aecdd8c18eb3d943c449126fd328f5dd7e.1710188056838",
  "phone": "+91 8451284512",
  "otp": 8991
}

###
GET  http://localhost:5000/api/refresh HTTP/1.1
Content-Type: application/json